# -*- coding: utf-8 -*-
"""Лидар.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mVgOIDKtxL8WVMpPxSwBXPowR2AqQIkq
"""

import pandas as pd
import matplotlib.pyplot as plt
import math


data = pd.read_csv('/content/drive/MyDrive/examp10.txt', sep=";", header=None)
coord = data[0].str.split(",", expand=True)
lidar = data[1].str.split(",", expand=True)



plt.figure(figsize=(10, 5))
X = pd.to_numeric(coord[0])
Y = pd.to_numeric(coord[1])
W = pd.to_numeric(coord[2])
#print(W)
plt.title("Coordinates")
xdir=[]
ydir=[]

ang=0.5
for i in range(0,len(coord[0])):   
    xdir.append(X[i] * math.cos(ang) + Y[i] * math.sin(ang))
    ydir.append(-X[i] * math.sin(ang) + Y[i] * math.cos(ang))

plt.scatter([xdir], [ydir], s=1, c='r')  

xlist=[]
ylist=[]


for j in range(0,len(lidar[0])) : 
    phi = 2.0944+W[j] 
    for i in range(680):      
       r=float((lidar[i][j]))    
       if ( r<5.6) and (r>0.3):  
           xw=(r)*math.cos(phi)+0.3
           yw = r * math.sin(phi)
           x0 = (X[j] + xw + 0.3*math.cos(W[j]))  
           y0 = (Y[j] + yw +0.3*math.sin(W[j]))
           xlist.append(x0)
           ylist.append(y0)
       phi=phi-0.006152716      


for i in range(len(xlist)):
       x1 = xlist[i]
       y1= ylist[i]
       xlist[i] = x1 * math.cos(ang) + y1 * math.sin(ang)
       ylist[i] = - x1 * math.sin(ang) + y1 * math.cos(ang)


plt.scatter(xlist, ylist,s=0.5, c='b')
plt.show()